"""remote_config table (S13)

Revision ID: d631f087e10c
Revises: a0ceab780d3b
Create Date: 2026-05-29 23:49:57.039443

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd631f087e10c'
down_revision: str | None = 'a0ceab780d3b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remote_config',
    sa.Column('monetization_mode', sa.Enum('DISCOVERY', 'PAID', 'MIXED', name='monetization_mode'), nullable=False),
    sa.Column('ai_kill_switch', sa.Boolean(), nullable=False),
    sa.Column('limits', sa.JSON(), nullable=False),
    sa.Column('feature_flags', sa.JSON(), nullable=False),
    sa.Column('ai_model_per_type', sa.JSON(), nullable=False),
    sa.Column('prompt_versions', sa.JSON(), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remote_config')
    # ### end Alembic commands ###
