"""initial schema

Revision ID: 7059fd65afd5
Revises: 
Create Date: 2026-05-23 21:34:51.184281

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7059fd65afd5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('yandex_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_yandex_id'), ['yandex_id'], unique=True)

    op.create_table('credits',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('package', sa.Enum('MINI', 'STANDARD', 'BULK', name='credits_package'), nullable=False),
    sa.Column('operations_total', sa.Integer(), nullable=False),
    sa.Column('operations_used', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credits_user_id'), ['user_id'], unique=False)

    op.create_table('devices',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.Enum('WINDOWS', 'MACOS', 'LINUX', name='device_platform'), nullable=False),
    sa.Column('app_version', sa.String(length=32), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_ip_masked', sa.String(length=64), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fingerprint', name='uq_device_user_fingerprint')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_user_id'), ['user_id'], unique=False)

    op.create_table('payments',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('yookassa_payment_id', sa.String(length=128), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.Enum('SUBSCRIPTION', 'CREDITS', name='payment_purpose'), nullable=False),
    sa.Column('package_or_plan', sa.String(length=32), nullable=False),
    sa.Column('amount_kopecks', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'CANCELLED', 'REFUNDED', name='payment_status'), nullable=False),
    sa.Column('confirmation_url', sa.String(length=512), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_yookassa_payment_id'), ['yookassa_payment_id'], unique=True)

    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address_masked', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'PRO', name='subscription_plan'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAST_DUE', 'CANCELLED', 'EXPIRED', name='subscription_status'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('early_adopter', sa.Boolean(), nullable=False),
    sa.Column('price_locked_kopecks', sa.Integer(), nullable=False),
    sa.Column('yookassa_payment_method_id', sa.String(length=128), nullable=True),
    sa.Column('yookassa_subscription_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_subscription_user')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('telemetry_events',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('app_version', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telemetry_events_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_events_device_fingerprint'), ['device_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_events_user_id'), ['user_id'], unique=False)

    op.create_table('license_keys',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_device_id', sa.String(length=36), nullable=True),
    sa.Column('issued_for_payment_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['issued_for_payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['used_by_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('license_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_license_keys_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_license_keys_user_id'), ['user_id'], unique=False)

    op.create_table('usage',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('operation_type', sa.Enum('AI_EXPLANATION', 'AI_DEADLOCK_EXPLANATION', 'AI_REWRITE', 'AI_SLOW_QUERY_EXPLANATION', name='usage_operation_type'), nullable=False),
    sa.Column('archive_hash', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cost_credits', sa.Integer(), nullable=False),
    sa.Column('billed_against', sa.Enum('FREE_QUOTA', 'PRO_QUOTA', 'CREDITS_BALANCE', name='usage_billed_against'), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ai_tokens_input', sa.Integer(), nullable=True),
    sa.Column('ai_tokens_output', sa.Integer(), nullable=True),
    sa.Column('ai_cost_usd', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_archive_hash'), ['archive_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_timestamp'))
        batch_op.drop_index(batch_op.f('ix_usage_device_id'))
        batch_op.drop_index(batch_op.f('ix_usage_archive_hash'))

    op.drop_table('usage')
    with op.batch_alter_table('license_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_license_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_license_keys_key'))

    op.drop_table('license_keys')
    with op.batch_alter_table('telemetry_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telemetry_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_telemetry_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_telemetry_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_telemetry_events_device_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_telemetry_events_category'))

    op.drop_table('telemetry_events')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_yookassa_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))

    op.drop_table('payments')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_user_id'))
        batch_op.drop_index(batch_op.f('ix_devices_fingerprint'))

    op.drop_table('devices')
    with op.batch_alter_table('credits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credits_user_id'))

    op.drop_table('credits')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_yandex_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
