"""drop desktop_sessions (email-only flow)

Revision ID: a0ceab780d3b
Revises: 454d49efcf59
Create Date: 2026-05-24 02:15:50.788840

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0ceab780d3b'
down_revision: str | None = '454d49efcf59'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desktop_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_desktop_sessions_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_desktop_sessions_user_id'))

    op.drop_table('desktop_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desktop_sessions',
    sa.Column('fingerprint', sa.VARCHAR(length=64), nullable=False),
    sa.Column('device_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('platform', sa.VARCHAR(length=16), nullable=False),
    sa.Column('app_version', sa.VARCHAR(length=32), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('device_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('issued_access_token', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('confirmed_at', sa.DATETIME(), nullable=True),
    sa.Column('claimed_at', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('desktop_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_desktop_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_desktop_sessions_fingerprint'), ['fingerprint'], unique=False)

    # ### end Alembic commands ###
