"""add desktop_sessions table

Revision ID: a34817de709b
Revises: 7059fd65afd5
Create Date: 2026-05-24 01:12:33.657532

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a34817de709b'
down_revision: str | None = '7059fd65afd5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desktop_sessions',
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('app_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CLAIMED', 'EXPIRED', 'CANCELLED', name='desktop_session_status'), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('issued_access_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('desktop_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_desktop_sessions_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_desktop_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desktop_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_desktop_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_desktop_sessions_fingerprint'))

    op.drop_table('desktop_sessions')
    # ### end Alembic commands ###
